<a href="https://colab.research.google.com/github/Sachinsarth10/logistic-regression-model/blob/main/Copy_of_Covid_hospitilization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [ ]:
data=pd.read_csv("covis.csv")
x=data.iloc[:,:5].values
y=data.iloc[:,5:6].values


In [ ]:
print(x)
print(y)

[[10.0 'Moderate' 'no' 'no' 97.0]
 [12.0 'Moderate' 'no' 'no' 97.0]
 [15.0 'Moderate' 'no' 'no' 94.0]
 [10.0 'Moderate' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 94.0]
 [12.0 'Moderate' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 93.0]
 [15.0 'Moderate' 'no' 'no' 92.0]
 [18.0 'Moderate' 'no' 'no' 66.0]
 [19.0 'Moderate' 'no' 'no' 92.0]
 [20.0 'Moderate' 'no' 'no' 93.0]
 [17.0 'Moderate' 'no' 'no' 93.0]
 [16.0 'Moderate' 'no' 'no' 92.0]
 [18.0 'Moderate' 'no' 'no' 93.0]
 [20.0 'Moderate' 'no' 'no' 92.0]
 [25.0 'Moderate' 'no' 'no' 93.0]
 [24.0 'Moderate' 'no' 'no' 92.0]
 [26.0 'High' 'no' 'no' 94.0]
 [28.0 'Moderate' 'no' 'no' 99.0]
 [29.0 'Moderate' 'no' 'no' 93.0]
 [30.0 'Moderate' 'no' 'no' 62.0]
 [19.0 'Moderate' 'no' 'no' 89.0]
 [25.0 'Moderate' 'no' 'yes' 86.0]
 [26.0 'Moderate' 'no' 'no' nan]
 [28.0 'Moderate' 'no' 'no' 89.0]
 [30.0 'Moderate' 'yes' 'no' 86.0]
 [35.0 'Moderate' 'no' 'no' 89.0]
 [32.0 'Moderate' 'no' 'yes' 84.0]
 [nan 'Moderate' 'yes' 'no' 90.0]
 [32.0 'Moderate

In [ ]:
data.isnull().sum()

age                              1
body_temperature                 0
chronic_disease                  0
breathing_issue                  0
Blood O2 Level in Percentage     1
Needed Hospitalization           0
Unnamed: 6                      69
dtype: int64

In [ ]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan, strategy="mean")
imputer.fit(x[:,:1])
x[:,:1]=imputer.transform(x[:,:1])
print(x)


[[10.0 'Moderate' 'no' 'no' 97.0]
 [12.0 'Moderate' 'no' 'no' 97.0]
 [15.0 'Moderate' 'no' 'no' 94.0]
 [10.0 'Moderate' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 94.0]
 [12.0 'Moderate' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 93.0]
 [15.0 'Moderate' 'no' 'no' 92.0]
 [18.0 'Moderate' 'no' 'no' 66.0]
 [19.0 'Moderate' 'no' 'no' 92.0]
 [20.0 'Moderate' 'no' 'no' 93.0]
 [17.0 'Moderate' 'no' 'no' 93.0]
 [16.0 'Moderate' 'no' 'no' 92.0]
 [18.0 'Moderate' 'no' 'no' 93.0]
 [20.0 'Moderate' 'no' 'no' 92.0]
 [25.0 'Moderate' 'no' 'no' 93.0]
 [24.0 'Moderate' 'no' 'no' 92.0]
 [26.0 'High' 'no' 'no' 94.0]
 [28.0 'Moderate' 'no' 'no' 99.0]
 [29.0 'Moderate' 'no' 'no' 93.0]
 [30.0 'Moderate' 'no' 'no' 62.0]
 [19.0 'Moderate' 'no' 'no' 89.0]
 [25.0 'Moderate' 'no' 'yes' 86.0]
 [26.0 'Moderate' 'no' 'no' nan]
 [28.0 'Moderate' 'no' 'no' 89.0]
 [30.0 'Moderate' 'yes' 'no' 86.0]
 [35.0 'Moderate' 'no' 'no' 89.0]
 [32.0 'Moderate' 'no' 'yes' 84.0]
 [45.130434782608695 'Moderate' 'yes' 'no' 90.0]
 

In [ ]:
imputer.fit(x[:,4:5])
x[:,4:5]=imputer.transform(x[:,4:5])
print(x)

[[10.0 'Moderate' 'no' 'no' 97.0]
 [12.0 'Moderate' 'no' 'no' 97.0]
 [15.0 'Moderate' 'no' 'no' 94.0]
 [10.0 'Moderate' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 94.0]
 [12.0 'Moderate' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 93.0]
 [15.0 'Moderate' 'no' 'no' 92.0]
 [18.0 'Moderate' 'no' 'no' 66.0]
 [19.0 'Moderate' 'no' 'no' 92.0]
 [20.0 'Moderate' 'no' 'no' 93.0]
 [17.0 'Moderate' 'no' 'no' 93.0]
 [16.0 'Moderate' 'no' 'no' 92.0]
 [18.0 'Moderate' 'no' 'no' 93.0]
 [20.0 'Moderate' 'no' 'no' 92.0]
 [25.0 'Moderate' 'no' 'no' 93.0]
 [24.0 'Moderate' 'no' 'no' 92.0]
 [26.0 'High' 'no' 'no' 94.0]
 [28.0 'Moderate' 'no' 'no' 99.0]
 [29.0 'Moderate' 'no' 'no' 93.0]
 [30.0 'Moderate' 'no' 'no' 62.0]
 [19.0 'Moderate' 'no' 'no' 89.0]
 [25.0 'Moderate' 'no' 'yes' 86.0]
 [26.0 'Moderate' 'no' 'no' 82.07246376811594]
 [28.0 'Moderate' 'no' 'no' 89.0]
 [30.0 'Moderate' 'yes' 'no' 86.0]
 [35.0 'Moderate' 'no' 'no' 89.0]
 [32.0 'Moderate' 'no' 'yes' 84.0]
 [45.130434782608695 'Moderate' 'yes

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[("encoder",OneHotEncoder(),[1])],remainder="passthrough")
x=np.array(ct.fit_transform(x))
print(x)

[[0.0 1.0 10.0 'no' 'no' 97.0]
 [0.0 1.0 12.0 'no' 'no' 97.0]
 [0.0 1.0 15.0 'no' 'no' 94.0]
 [0.0 1.0 10.0 'no' 'no' 97.0]
 [0.0 1.0 13.0 'no' 'no' 94.0]
 [0.0 1.0 12.0 'no' 'no' 97.0]
 [0.0 1.0 13.0 'no' 'no' 93.0]
 [0.0 1.0 15.0 'no' 'no' 92.0]
 [0.0 1.0 18.0 'no' 'no' 66.0]
 [0.0 1.0 19.0 'no' 'no' 92.0]
 [0.0 1.0 20.0 'no' 'no' 93.0]
 [0.0 1.0 17.0 'no' 'no' 93.0]
 [0.0 1.0 16.0 'no' 'no' 92.0]
 [0.0 1.0 18.0 'no' 'no' 93.0]
 [0.0 1.0 20.0 'no' 'no' 92.0]
 [0.0 1.0 25.0 'no' 'no' 93.0]
 [0.0 1.0 24.0 'no' 'no' 92.0]
 [1.0 0.0 26.0 'no' 'no' 94.0]
 [0.0 1.0 28.0 'no' 'no' 99.0]
 [0.0 1.0 29.0 'no' 'no' 93.0]
 [0.0 1.0 30.0 'no' 'no' 62.0]
 [0.0 1.0 19.0 'no' 'no' 89.0]
 [0.0 1.0 25.0 'no' 'yes' 86.0]
 [0.0 1.0 26.0 'no' 'no' 82.07246376811594]
 [0.0 1.0 28.0 'no' 'no' 89.0]
 [0.0 1.0 30.0 'yes' 'no' 86.0]
 [0.0 1.0 35.0 'no' 'no' 89.0]
 [0.0 1.0 32.0 'no' 'yes' 84.0]
 [0.0 1.0 45.130434782608695 'yes' 'no' 90.0]
 [0.0 1.0 32.0 'no' 'no' 89.0]
 [0.0 1.0 35.0 'no' 'yes' 92.0]
 [1.0 0

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[("encoder",OneHotEncoder(),[3])],remainder="passthrough")
x=np.array(ct.fit_transform(x))
print(x)

[[1.0 0.0 0.0 1.0 10.0 'no' 97.0]
 [1.0 0.0 0.0 1.0 12.0 'no' 97.0]
 [1.0 0.0 0.0 1.0 15.0 'no' 94.0]
 [1.0 0.0 0.0 1.0 10.0 'no' 97.0]
 [1.0 0.0 0.0 1.0 13.0 'no' 94.0]
 [1.0 0.0 0.0 1.0 12.0 'no' 97.0]
 [1.0 0.0 0.0 1.0 13.0 'no' 93.0]
 [1.0 0.0 0.0 1.0 15.0 'no' 92.0]
 [1.0 0.0 0.0 1.0 18.0 'no' 66.0]
 [1.0 0.0 0.0 1.0 19.0 'no' 92.0]
 [1.0 0.0 0.0 1.0 20.0 'no' 93.0]
 [1.0 0.0 0.0 1.0 17.0 'no' 93.0]
 [1.0 0.0 0.0 1.0 16.0 'no' 92.0]
 [1.0 0.0 0.0 1.0 18.0 'no' 93.0]
 [1.0 0.0 0.0 1.0 20.0 'no' 92.0]
 [1.0 0.0 0.0 1.0 25.0 'no' 93.0]
 [1.0 0.0 0.0 1.0 24.0 'no' 92.0]
 [1.0 0.0 1.0 0.0 26.0 'no' 94.0]
 [1.0 0.0 0.0 1.0 28.0 'no' 99.0]
 [1.0 0.0 0.0 1.0 29.0 'no' 93.0]
 [1.0 0.0 0.0 1.0 30.0 'no' 62.0]
 [1.0 0.0 0.0 1.0 19.0 'no' 89.0]
 [1.0 0.0 0.0 1.0 25.0 'yes' 86.0]
 [1.0 0.0 0.0 1.0 26.0 'no' 82.07246376811594]
 [1.0 0.0 0.0 1.0 28.0 'no' 89.0]
 [0.0 1.0 0.0 1.0 30.0 'no' 86.0]
 [1.0 0.0 0.0 1.0 35.0 'no' 89.0]
 [1.0 0.0 0.0 1.0 32.0 'yes' 84.0]
 [0.0 1.0 0.0 1.0 45.130434782608

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[("encoder",OneHotEncoder(),[5])],remainder="passthrough")
x=np.array(ct.fit_transform(x))
print(x)

[[1.0 0.0 1.0 0.0 0.0 1.0 10.0 97.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 12.0 97.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 15.0 94.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 10.0 97.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 13.0 94.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 12.0 97.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 13.0 93.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 15.0 92.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 18.0 66.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 19.0 92.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 20.0 93.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 17.0 93.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 16.0 92.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 18.0 93.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 20.0 92.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 25.0 93.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 24.0 92.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 26.0 94.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 28.0 99.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 29.0 93.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 30.0 62.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 19.0 89.0]
 [0.0 1.0 1.0 0.0 0.0 1.0 25.0 86.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 26.0 82.07246376811594]
 [1.0 0.0 1.0 0.0 0.0 1.0 28.0 89.0]
 [1.0 0.0 0.0 1.0 0.0 1.0 30.0 86.0]
 [1.0 0.0 1.0 0.0 0.0 1.0

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)
print(y)

[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1]


/usr/local/lib/python3.11/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
print(x_train)

[[0.0 1.0 0.0 1.0 1.0 0.0 86.0 71.0]
 [0.0 1.0 1.0 0.0 0.0 1.0 35.0 92.0]
 [0.0 1.0 1.0 0.0 1.0 0.0 75.0 72.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 42.0 92.0]
 [0.0 1.0 0.0 1.0 1.0 0.0 74.0 75.0]
 [0.0 1.0 0.0 1.0 1.0 0.0 62.0 68.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 24.0 92.0]
 [0.0 1.0 1.0 0.0 0.0 1.0 48.0 93.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 58.0 70.0]
 [1.0 0.0 0.0 1.0 0.0 1.0 45.130434782608695 90.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 15.0 92.0]
 [0.0 1.0 1.0 0.0 0.0 1.0 70.0 88.0]
 [0.0 1.0 0.0 1.0 1.0 0.0 52.0 80.0]
 [0.0 1.0 0.0 1.0 1.0 0.0 60.0 68.0]
 [0.0 1.0 0.0 1.0 1.0 0.0 54.0 70.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 29.0 93.0]
 [0.0 1.0 0.0 1.0 1.0 0.0 78.0 71.0]
 [1.0 0.0 0.0 1.0 1.0 0.0 36.0 90.0]
 [1.0 0.0 0.0 1.0 0.0 1.0 30.0 86.0]
 [0.0 1.0 0.0 1.0 1.0 0.0 50.0 77.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 18.0 93.0]
 [0.0 1.0 1.0 0.0 1.0 0.0 69.0 53.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 10.0 97.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 26.0 94.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 18.0 66.0]
 [0.0 1.0 0.0 1.0 1.0 0.0 62.0 69.0]
 [1.0 0.0 1.0 0.0 0.0 1.

In [ ]:
print(x_test)

[[0.0 1.0 1.0 0.0 0.0 1.0 25.0 86.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 10.0 97.0]
 [1.0 0.0 0.0 1.0 1.0 0.0 68.0 67.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 13.0 94.0]
 [1.0 0.0 0.0 1.0 1.0 0.0 59.0 68.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 28.0 99.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 20.0 93.0]
 [1.0 0.0 0.0 1.0 1.0 0.0 46.0 91.0]
 [1.0 0.0 0.0 1.0 1.0 0.0 53.0 55.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 16.0 92.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 38.0 75.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 19.0 92.0]
 [0.0 1.0 0.0 1.0 1.0 0.0 94.0 64.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 12.0 97.0]]


In [ ]:
print(y_test)

[0 0 1 0 1 0 0 0 1 0 1 0 1 0]


In [ ]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression()
classifier.fit(x_train,y_train)



LogisticRegression()

In [ ]:
y_pred=classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]]


In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,classifier.predict(x_test))


1.0

In [ ]:
x_new=np.array([1.0 ,0.0, 1.0, 0.0, 0.0, 1.0, 10.0, 97.0,])

print(x_new)

[ 1.  0.  1.  0.  0.  1. 10. 97.]


In [ ]:

y_pred=classifier.predict(x_new.reshape(1,-1))
le=LabelEncoder()
le.fit(['yes','no'])
y_pred=le.inverse_transform(y_pred)
print(y_pred)



['no']
